package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"cawall-be/graph"
	"cawall-be/graph/gqlmodel"
	"context"
	"fmt"
)

// Done is the resolver for the done field.
func (r *todoResolver) Done(ctx context.Context, obj *gqlmodel.Todo) (bool, error) {
	panic(fmt.Errorf("not implemented: Done - done"))
}

// Todos is the resolver for the todos field.
func (r *todoQueryResolver) Todos(ctx context.Context, obj *gqlmodel.TodoQuery) ([]*gqlmodel.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

// TodoQuery returns graph.TodoQueryResolver implementation.
func (r *Resolver) TodoQuery() graph.TodoQueryResolver { return &todoQueryResolver{r} }

type todoResolver struct{ *Resolver }
type todoQueryResolver struct{ *Resolver }
